[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev:vite"
  targetPort = 5173
  port = 8888

[[redirects]]
  # Route any request to /api/* to the serverless functions directory
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true


